export const browserCoreExamples = [
  "openjordy browser status",
  "openjordy browser start",
  "openjordy browser stop",
  "openjordy browser tabs",
  "openjordy browser open https://example.com",
  "openjordy browser focus abcd1234",
  "openjordy browser close abcd1234",
  "openjordy browser screenshot",
  "openjordy browser screenshot --full-page",
  "openjordy browser screenshot --ref 12",
  "openjordy browser snapshot",
  "openjordy browser snapshot --format aria --limit 200",
  "openjordy browser snapshot --efficient",
  "openjordy browser snapshot --labels",
];

export const browserActionExamples = [
  "openjordy browser navigate https://example.com",
  "openjordy browser resize 1280 720",
  "openjordy browser click 12 --double",
  'openjordy browser type 23 "hello" --submit',
  "openjordy browser press Enter",
  "openjordy browser hover 44",
  "openjordy browser drag 10 11",
  "openjordy browser select 9 OptionA OptionB",
  "openjordy browser upload /tmp/openjordy/uploads/file.pdf",
  'openjordy browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openjordy browser dialog --accept",
  'openjordy browser wait --text "Done"',
  "openjordy browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openjordy browser console --level error",
  "openjordy browser pdf",
];
